account/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import login_view, register_user
app_name = "account"

urlpatterns = [
    path('login', login_view, name="login"),
    path('register', register_user, name="register"),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path("", include("home.urls"))
]

home/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import IndexView, DetailRouter, ListRouters, AddRouter

app_name = "home"

urlpatterns = [
    path('', login_required(IndexView.as_view()), name="index"),
    path('addrouter', login_required(AddRouter.as_view()), name='addrouter'),
    path('listrouters', login_required(ListRouters.as_view()), name="listrouters"),
    path('detail/<uuid:serialnumber>', login_required(DetailRouter.as_view()), name='details')
]

home/models.py
import uuid

from django.db import models

# Create your models here.


class Routers(models.Model):
    serialnumber = models.CharField(max_length=255, primary_key=True)
    username = models.CharField(max_length=255)
    routername = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    enterprise = models.CharField(max_length=255)
    ipaddress = models.GenericIPAddressField()

    def __str__(self):
        return "Le routeur {}:{} appartient à {}".format(self.routername, self.serialnumber, self.enterprise)


class Logs(models.Model):
    log_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    time = models.DateTimeField()
    topics = models.CharField(max_length=300)
    message = models.TextField()
    router = models.ForeignKey(Routers, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-time']

home/forms.py
from django import forms


class RouterForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    ipaddress = forms.GenericIPAddressField(
        label="IP Address",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            })
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ))
    enterprise = forms.CharField(
        label="Enterprise",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

home/views.py
import datetime

import ros_api

from django.contrib import messages
from django.views import generic
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from .forms import RouterForm
from .models import Routers, Logs
from .functions_utils import encrypt, generate_serial_number, check_if_router_is_online, decrypt


# Create your views here.

# Displays general information about administrated routers
class IndexView(generic.TemplateView):
    template_name = "home/index.html"
    context_object_name = "logs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        routers = []
        for router in Routers.objects.all():
            router = vars(router)
            router.pop('password')
            router.pop('_state')
            if check_if_router_is_online(ipaddress=router['ipaddress']):
                router['status'] = True
                routers.append(router)
            else:
                router['status'] = False
                routers.append(router)
        context['routers'] = routers
        context['logs'] = Logs.objects.all()
        # context['logs'] = Logs.objects.all()
        return context

    def get_queryset(self):
        """:return: all logs"""
        return Logs.objects.all()


# Form to save information about a router
class AddRouter(FormView):
    template_name = "home/addrouter.html"
    form_class = RouterForm
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        addrouter_data = self.request.POST
        username = addrouter_data["username"]
        ipaddress = addrouter_data["ipaddress"]
        password = addrouter_data["password"]
        enterprise = addrouter_data["enterprise"]

        connexion_mikrotik = ros_api.Api(ipaddress, user=username, password=password)
        if connexion_mikrotik.is_alive():
            password_save = encrypt(password)
            saverouter = Routers(serialnumber=generate_serial_number(), username=username,
                                 routername=connexion_mikrotik.talk("/system/identity/print")[0]['name'],
                                 enterprise=enterprise,
                                 ipaddress=ipaddress,
                                 password=password_save)
            saverouter.save()
            messages.success(self.request, "Saved Router")
            for log in connexion_mikrotik.talk("/log/print"):
                Logs(time=datetime.datetime.combine(datetime.date.today(),
                                                    datetime.time(*map(int, log['time'].split(":")))),
                     topics=log['topics'].replace(",", "."),
                     message=log['message'],
                     router=saverouter).save()

            return super().form_valid(form)
        else:
            messages.error(self.request, "We can't connect to Router")
            return super().form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


# List administrated routers
class ListRouters(generic.ListView):
    model = Routers
    template_name = "home/listRouters.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        routers = []
        for router in Routers.objects.all():
            router = vars(router)
            router.pop('password')
            router.pop('_state')
            if check_if_router_is_online(ipaddress=router['ipaddress']):
                router['status'] = True
                routers.append(router)
            else:
                router['status'] = False
                routers.append(router)
        context['routers'] = routers
        # context['routers'] = Routers.objects.all()
        return context


# Give information about specific router
class DetailRouter(generic.DetailView):
    template_name = 'home/detailRouter.html'
    model = Routers

    def get_object(self, queryset=None):
        return Routers.objects.get(serialnumber=self.kwargs.get("serialnumber"))

    def setup(self, request, **kwargs):
        super().setup(request, **kwargs)
        router = self.get_object()
        self.connexion = ros_api.Api(user=router.username, password=decrypt(router.password),
                                     address=router.ipaddress)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['interfaces'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                 for information in self.connexion.talk("/interface/print")]
        context['ports'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/port/print")]
        context['operating_statistics'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                           for information in self.connexion.talk("/system/resource/print")]
        context['active_users'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                   for information in self.connexion.talk("/user/active/print")]
        context['ipaddresses'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                  for information in self.connexion.talk("/ip/address/print")]
        context['ports'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/port/print")]
        context['files'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/file/print")]
        context['packages'] = [{k.replace("-", "_"): v for k, v in information.items()}
                               for information in self.connexion.talk("/system/package/print")]
        context['daily_data_streams'] = [
            {'name': interface['name'], 'rx_byte': interface['rx-byte'], 'tx_byte': interface['tx-byte'],
             'rx_packet': interface["rx-packet"], 'tx_packet': interface["tx-packet"]}
            for interface in self.connexion.talk("/interface/print")]

        print(context["daily_data_streams"])

        return context

templates/home/addrouter.html
{% extends "home/base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock title %}
<!-- Specific Page CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add router</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Add router</li>
            </ol>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <!-- Form Basic -->
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Add Router</h6>
                </div>
                <div class="card-body">
                  <form method="post">
                    {% csrf_token %}
                    {% if errors %}
                      errors
                    {% endif %}
                    {% for field in form %}
                      <div class="form-group">
                        {% if field.errors %}
                        <ol>
                          {% for error in field.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                          {% endfor %}
                        </ol>
                        {% endif %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.help_text %}
                          <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                      </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>

            </div>
          </div>

</div>
{% endblock content %}

templates/home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="{% static 'img/logo/logo.png' %}" rel="icon">
  <title>{% block title %}{% endblock title %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" integrity="sha512-rqQltXRuHxtPWhktpAZxLHUVJ3Eombn3hvk9PHjV/N5DMUYnzKPC1i3ub0mEXgFzsaZNeJcoE0YHq0j/GFsdGg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha512-oc9+XSs1H243/FRN9Rw62Fn8EtxjEYWHXRvjS43YtueEewbS6ObfXcJNyohjHqVKFPoXXUxwc+q1K7Dee6vv9g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="{% static 'css/ruang-admin.min.css' %}" rel="stylesheet">


  <!-- Specific Page CSS goes HERE -->
  {% block stylesheets %}{% endblock stylesheets %}
</head>


<body id="page-top">
  <div id="wrapper">
    <!-- Sidebar -->
    {% include 'home/includes/sidebar.html' %}
    <!-- Sidebar -->
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
        <!-- TopBar -->
        {% include 'home/includes/topbar.html' %}
        <!-- Topbar -->
          {% if messages %}
              <div aria-live="polite" aria-atomic="true" style="position: relative;" class="toast-container">
            {% for message in messages %}
                <div style="position: absolute; top:0; right:0;">
                  <div class="toast {% if message.tags %}{{ message.tags }}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header">
                      <strong>Notifications</strong>
                    </div>
                    <div class="toast-body">
                      {{ message }}
                      <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>

                  </div>
                </div>
            {% endfor %}
              </div>
          {% endif %}
        <!-- Container Fluid-->
        {% block content %} {% endblock content %}
        <!---Container Fluid-->
      </div>
    </div>
  </div>

  <!-- Modal Logout -->
          <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to logout?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                  <a href="{% url 'account:logout' %}" class="btn btn-primary">Logout</a>
                </div>
              </div>
            </div>
          </div>


  <!-- Scroll to top -->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <script type="text/javascript">
    $('.toast').toast({
      delay: 5000
      });
    $('.toast').toast('show');
  </script>

  <script src="{% static 'js/ruang-admin.min.js' %}"></script>
  <!-- Specific Page JS goes HERE -->
  {% block javascripts %} {% endblock javascripts %}

</body>

</html>

templates/home/index.html
{% extends "home/base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock title %}
<!-- Specific Page CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid" id="container-wrapper">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
        </ol>
    </div>
    {% comment %}
    <div class="row mb-4">
        <div class="col-col-3 col-md-4 mb-3">
            <div class="card">
                <div class="card-header">Online</div>
                <div class="card-body">
                    <div class="h2 mb-0 font-weight-bold text-gray-800"> 8 </div>
                    <div class="mt-2 mb-0 text-muted text-xs">
                        <span>Routers</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-col-3 col-md-4 mb-3">
            <div class="card">
                <div class="card-header">Offline</div>
                <div class="card-body">
                    <div class="h2 mb-0 font-weight-bold text-gray-800"> 12 </div>
                    <div class="mt-2 mb-0 text-muted text-xs">
                        <span>Routers</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-col-3 col-md-4 mb-3">
            <div class="card">
                <div class="card-header">Clients</div>
                <div class="card-body">
                    <div class="h2 mb-0 font-weight-bold text-gray-800"> 10 </div>
                    <div class="mt-2 mb-0 text-muted text-xs">
                        <span>Online</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endcomment %}

    <div class="row">
        <!-- List Devices -->
            <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">List Routers</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush" id="ListRouters">
                    <thead class="thead-light">
                      <tr>
                        <th>Serial Number</th>
                        <th>Router Name</th>
                        <th>Enterprise</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for router in routers %}

                        <tr>
                            {% if router.status %}
                            <td><a href="{% url 'home:details' router.serialnumber %}">{{ router.serialnumber }}</a></td>
                            {% else %}
                            <td><a href="{% url 'home:details' router.serialnumber %}">{{ router.serialnumber }} (inactif)</a></td>
                            {% endif %}
                            <td>{{ router.routername }}</td>
                            <td>{{ router.enterprise }}</td>
                            {% if router.status %}
                            <td><span class="badge badge-success">Online</span></td>
                            {% else %}
                            <td><span class="badge badge-danger">Offline</span></td>
                            {% endif %}

                        </tr>

                    {% endfor %}


                    </tbody>
                  </table>
                </div>
              </div>
            </div>
      <!-- end List Routers -->
            <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Views Logs</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover2">
                    <thead class="thead-light">
                      <tr>
                        <th>Serail Number</th>
                        <th>RouterName</th>
                        <th>topics</th>
                        <th>message</th>
                        <th>time</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>Serail Number</th>
                        <th>RouterName</th>
                        <th>topics</th>
                        <th>message</th>
                        <th>time</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for log in logs %}
                        <tr>
                          <td><a href="{% url 'home:details' log.router_id %}">{{ log.router_id }}</a></td>
                          <td>{{ log.router.routername }}</td>
                          <td>{{ log.topics }}</td>
                          <td>{{ log.message }}</td>
                          <td>{{ log.time }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        <!-- Area Charts -->

    </div>
</div>
{% endblock content %}


    {% block javascripts %}
<!-- Page level plugins -->
 <!--- <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script> -->
<script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<!-- Page level custom scripts -->
<!-- Page level plugins -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap4.min.js"></script>

  <!-- <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>-->
 <!-- Page level custom scripts -->
  <script>
    $(document).ready(function () {
      $('#dataTableHover2').DataTable(); // ID From dataTable with Hover
    });
  </script>
{% endblock javascripts %}

templates/home/listRouters.html
{% extends "home/base.html" %}
{% load static %}
{% block title %} List Routers {% endblock title %}
<!-- Specific Page CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">List Routers</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'home:index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">List Routers</li>
            </ol>
          </div>
    <div class="row">
        <!-- DataTable with Hover -->
            <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">List Routers</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                    <thead class="thead-light">
                      <tr>
                        <th>Serial Number</th>
                        <th>Router Name</th>
                        <th>Enterprise</th>
                        <th>Status</th>
                      </tr>
                    </thead>
                    <tfoot>
                      <tr>
                        <th>Serial Number</th>
                        <th>Router Name</th>
                        <th>Enterprse</th>
                        <th>Status</th>
                      </tr>
                    </tfoot>
                    <tbody>
                      {% for router in routers %}
                        <tr>
                          <td><a href="{% url 'home:details' router.serialnumber %}">{{ router.serialnumber }}</a></td>
                          <td>{{ router.routername }}</td>
                          <td>{{ router.enterprise }}</td>
                          <td>{{ router.status }}</td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
    </div>

</div>

{% endblock content %}

{% block javascripts %}
<!-- Page level plugins -->
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap4.min.js"></script>
 <!-- Page level custom scripts -->
  <script>
    $(document).ready(function () {
      $('#dataTableHover').DataTable(); // ID From dataTable with Hover
    });
  </script>
{% endblock javascripts %}

templates/home/sidebar.html
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon">
          <img src="img/logo/logo2.png">
        </div>
        <div class="sidebar-brand-text mx-3">RuangAdmin</div>
      </a>
      <hr class="sidebar-divider my-0">
      <li class="nav-item active">
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <hr class="sidebar-divider">
      <div class="sidebar-heading">
        Features
      </div>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBootstrap"
          aria-expanded="true" aria-controls="collapseBootstrap">
          <i class="far fa-fw fa-window-maximize"></i>
          <span>Bootstrap UI</span>
        </a>
        <div id="collapseBootstrap" class="collapse" aria-labelledby="headingBootstrap" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Bootstrap UI</h6>
            <a class="collapse-item" href="alerts.html">Alerts</a>
            <a class="collapse-item" href="buttons.html">Buttons</a>
            <a class="collapse-item" href="dropdowns.html">Dropdowns</a>
            <a class="collapse-item" href="modals.html">Modals</a>
            <a class="collapse-item" href="popovers.html">Popovers</a>
            <a class="collapse-item" href="progress-bar.html">Progress Bars</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseForm" aria-expanded="true"
          aria-controls="collapseForm">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Forms</span>
        </a>
        <div id="collapseForm" class="collapse" aria-labelledby="headingForm" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Forms</h6>
            <a class="collapse-item" href="form_basics.html">Form Basics</a>
            <a class="collapse-item" href="form_advanceds.html">Form Advanceds</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTable" aria-expanded="true"
          aria-controls="collapseTable">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span>
        </a>
        <div id="collapseTable" class="collapse" aria-labelledby="headingTable" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Tables</h6>
            <a class="collapse-item" href="simple-tables.html">Simple Tables</a>
            <a class="collapse-item" href="datatables.html">DataTables</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="ui-colors.html">
          <i class="fas fa-fw fa-palette"></i>
          <span>UI Colors</span>
        </a>
      </li>
      <hr class="sidebar-divider">
      <div class="sidebar-heading">
        Examples
      </div>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePage" aria-expanded="true"
          aria-controls="collapsePage">
          <i class="fas fa-fw fa-columns"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePage" class="collapse" aria-labelledby="headingPage" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Example Pages</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span>
        </a>
      </li>
      <hr class="sidebar-divider">
      <div class="version" id="version-ruangadmin"></div>
    </ul>