core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls")),
    path("", include("home.urls"))
]

home/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import IndexView, DetailRouter, ListRouters, AddRouter

app_name = "home"

urlpatterns = [
    path('', login_required(IndexView.as_view()), name="index"),
    path('addrouter', login_required(AddRouter.as_view()), name='addrouter'),
    path('listrouters', login_required(ListRouters.as_view()), name="listrouters"),
    path('detail/<uuid:serialnumber>', login_required(DetailRouter.as_view()), name='details')
]

home/models.py
import uuid

from django.db import models

# Create your models here.


class Routers(models.Model):
    serialnumber = models.CharField(max_length=255, primary_key=True)
    username = models.CharField(max_length=255)
    routername = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    enterprise = models.CharField(max_length=255)
    ipaddress = models.GenericIPAddressField()

    def __str__(self):
        return "Le routeur {}:{} appartient à {}".format(self.routername, self.serialnumber, self.enterprise)


class Logs(models.Model):
    log_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    time = models.DateTimeField()
    topics = models.CharField(max_length=300)
    message = models.TextField()
    router = models.ForeignKey(Routers, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-time']

home/forms.py
from django import forms


class RouterForm(forms.Form):
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    ipaddress = forms.GenericIPAddressField(
        label="IP Address",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            })
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        ))
    enterprise = forms.CharField(
        label="Enterprise",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

home/views.py
import datetime

import ros_api

from django.contrib import messages
from django.views import generic
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from .forms import RouterForm
from .models import Routers, Logs
from .functions_utils import encrypt, generate_serial_number, check_if_router_is_online, decrypt


# Create your views here.

# Displays general information about administrated routers
class IndexView(generic.TemplateView):
    template_name = "home/index.html"
    context_object_name = "logs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        routers = []
        for router in Routers.objects.all():
            router = vars(router)
            router.pop('password')
            router.pop('_state')
            if check_if_router_is_online(ipaddress=router['ipaddress']):
                router['status'] = True
                routers.append(router)
            else:
                router['status'] = False
                routers.append(router)
        context['routers'] = routers
        context['logs'] = Logs.objects.all()
        # context['logs'] = Logs.objects.all()
        return context

    def get_queryset(self):
        """:return: all logs"""
        return Logs.objects.all()


# Form to save information about a router
class AddRouter(FormView):
    template_name = "home/addrouter.html"
    form_class = RouterForm
    success_url = reverse_lazy('home:index')

    def form_valid(self, form):
        addrouter_data = self.request.POST
        username = addrouter_data["username"]
        ipaddress = addrouter_data["ipaddress"]
        password = addrouter_data["password"]
        enterprise = addrouter_data["enterprise"]

        connexion_mikrotik = ros_api.Api(ipaddress, user=username, password=password)
        if connexion_mikrotik.is_alive():
            password_save = encrypt(password)
            saverouter = Routers(serialnumber=generate_serial_number(), username=username,
                                 routername=connexion_mikrotik.talk("/system/identity/print")[0]['name'],
                                 enterprise=enterprise,
                                 ipaddress=ipaddress,
                                 password=password_save)
            saverouter.save()
            messages.success(self.request, "Saved Router")
            for log in connexion_mikrotik.talk("/log/print"):
                Logs(time=datetime.datetime.combine(datetime.date.today(),
                                                    datetime.time(*map(int, log['time'].split(":")))),
                     topics=log['topics'].replace(",", "."),
                     message=log['message'],
                     router=saverouter).save()

            return super().form_valid(form)
        else:
            messages.error(self.request, "We can't connect to Router")
            return super().form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


# List administrated routers
class ListRouters(generic.ListView):
    model = Routers
    template_name = "home/listRouters.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        routers = []
        for router in Routers.objects.all():
            router = vars(router)
            router.pop('password')
            router.pop('_state')
            if check_if_router_is_online(ipaddress=router['ipaddress']):
                router['status'] = True
                routers.append(router)
            else:
                router['status'] = False
                routers.append(router)
        context['routers'] = routers
        # context['routers'] = Routers.objects.all()
        return context


# Give information about specific router
class DetailRouter(generic.DetailView):
    template_name = 'home/detailRouter.html'
    model = Routers

    def get_object(self, queryset=None):
        return Routers.objects.get(serialnumber=self.kwargs.get("serialnumber"))

    def setup(self, request, **kwargs):
        super().setup(request, **kwargs)
        router = self.get_object()
        self.connexion = ros_api.Api(user=router.username, password=decrypt(router.password),
                                     address=router.ipaddress)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['interfaces'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                 for information in self.connexion.talk("/interface/print")]
        context['ports'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/port/print")]
        context['operating_statistics'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                           for information in self.connexion.talk("/system/resource/print")]
        context['active_users'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                   for information in self.connexion.talk("/user/active/print")]
        context['ipaddresses'] = [{k.replace("-", "_"): v for k, v in information.items()}
                                  for information in self.connexion.talk("/ip/address/print")]
        context['ports'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/port/print")]
        context['files'] = [{k.replace("-", "_"): v for k, v in information.items()}
                            for information in self.connexion.talk("/file/print")]
        context['packages'] = [{k.replace("-", "_"): v for k, v in information.items()}
                               for information in self.connexion.talk("/system/package/print")]
        context['daily_data_streams'] = [
            {'name': interface['name'], 'rx_byte': interface['rx-byte'], 'tx_byte': interface['tx-byte'],
             'rx_packet': interface["rx-packet"], 'tx_packet': interface["tx-packet"]}
            for interface in self.connexion.talk("/interface/print")]

        print(context["daily_data_streams"])

        return context

templates/home/includes/sidebar.html
{% load static %}
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home:index' %}">
        <div class="sidebar-brand-icon">
          <img src="{% static 'img/logo/logo2.png' %}">
        </div>
        <div class="sidebar-brand-text mx-3">InControl2</div>
      </a>
      <hr class="sidebar-divider my-0">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      <hr class="sidebar-divider">
      <div class="sidebar-heading">
        Features
      </div>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'home:addrouter' %}">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Add Router</span>
        </a>
      </li>
          <li class="nav-item">
        <a class="nav-link" href="{%url 'home:listrouters' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>List Routers</span>
        </a>
      </li>
        <!--
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span>
        </a>
      </li> -->
      <hr class="sidebar-divider">
      <div class="version" id="version-ruangadmin"></div>
    </ul>

templates/home/includes/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
          <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-1 small" placeholder="What do you want to look for?"
                      aria-label="Search" aria-describedby="basic-addon2" style="border-color: #3f51b5;">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>
            {% comment %}
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <span class="badge badge-warning badge-counter">2</span>
              </a>
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="{% static 'img/man.png' %}" style="max-width: 60px" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been
                      having.</div>
                    <div class="small text-gray-500">Udin Cilok · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="{% static 'img/girl.png' %}" style="max-width: 60px" alt="">
                    <div class="status-indicator bg-default"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people
                      say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Jaenab · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-tasks fa-fw"></i>
                <span class="badge badge-success badge-counter">3</span>
              </a>
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Task
                </h6>
                <a class="dropdown-item align-items-center" href="#">
                  <div class="mb-3">
                    <div class="small text-gray-500">Design Button
                      <div class="small float-right"><b>50%</b></div>
                    </div>
                    <div class="progress" style="height: 12px;">
                      <div class="progress-bar bg-success" role="progressbar" style="width: 50%" aria-valuenow="50"
                        aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </a>
                <a class="dropdown-item align-items-center" href="#">
                  <div class="mb-3">
                    <div class="small text-gray-500">Make Beautiful Transitions
                      <div class="small float-right"><b>30%</b></div>
                    </div>
                    <div class="progress" style="height: 12px;">
                      <div class="progress-bar bg-warning" role="progressbar" style="width: 30%" aria-valuenow="30"
                        aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </a>
                <a class="dropdown-item align-items-center" href="#">
                  <div class="mb-3">
                    <div class="small text-gray-500">Create Pie Chart
                      <div class="small float-right"><b>75%</b></div>
                    </div>
                    <div class="progress" style="height: 12px;">
                      <div class="progress-bar bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75"
                        aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">View All Taks</a>
              </div>
            </li>
            {% endcomment %}
            <div class="topbar-divider d-none d-sm-block"></div>
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <img class="img-profile rounded-circle" src="{% static 'img/boy.png' %}" style="max-width: 60px">
                {% comment %}<span class="ml-2 d-none d-lg-inline text-white small">Maman Ketoprak</span> {% endcomment %}
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                {% comment %}
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                {% endcomment %}
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="javascript:void(0);" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>